Property test vec new approach
demergent-labs/azle pull request #1461
Opened 2023-11-30 05:26 UTC by bdemann

2023-12-01 04:37 UTC, bdemann commented on property_tests/arbitraries/candid/constructed/opt_arb/base.ts
> +export function OptDefinitionArb(
Break all of these into their own files

2023-12-01 18:19 UTC, dansteren requested changes

2023-12-01 18:19 UTC, dansteren commented on property_tests/arbitraries/candid/constructed/blob_arb/definition.ts
Rename this to have _arb in the name.

2023-12-01 18:19 UTC, dansteren commented on property_tests/arbitraries/candid/constructed/blob_arb/values.ts
add _arb to name.

2023-12-01 18:19 UTC, dansteren commented on property_tests/arbitraries/candid/constructed/variant_arb/definition_arbs.ts
> +    const fieldImports = fields.flatMap((field) => [
Consider destructuring to make this more readable what field[1] is. This is done in multiple places so do a pass to try to catch all these. I.e. go find all occurrences of this.

```suggestion
    const fieldImports = fields.flatMap(([name, definition]) => [
```

2023-12-01 22:43 UTC, lastmjs requested changes

2023-12-01 22:43 UTC, lastmjs commented on property_tests/arbitraries/candid/value_and_meta_arb.ts
> + * **Note:** This currently only supports ints, nats, and null arbitraries
Delete this part of the comment

2023-12-01 22:43 UTC, lastmjs commented on property_tests/arbitraries/candid/primitive/bool.ts
> +export const BoolDefinitionArb: fc.Arbitrary<BoolCandidDefinition> =
Remove all of these static type definitions in all files

2023-12-01 22:43 UTC, lastmjs commented on property_tests/arbitraries/candid/primitive/bool.ts
> +export const BoolArb = SimpleCandidValueAndMetaArb(
SimpleCandidValueAndMetaArb should cease to exist and be replaced with ComplexCandidValueAndMetaArb...rename it to CandidValueAndMetaArbCreator or something

2023-12-02 00:22 UTC, lastmjs approved these changes

2023-12-02 01:23 UTC, merged