Http functionality
demergent-labs/azle pull request #1582
Opened 2024-01-25 18:56 UTC by lastmjs

2024-01-25 20:07 UTC, bdemann approved these changes

2024-01-25 23:52 UTC, bdemann requested changes

2024-01-25 23:52 UTC, bdemann commented on src/lib/server.ts
> +globalThis._azleHttpResponse = HttpResponse;
get rid of these

2024-01-25 23:52 UTC, bdemann commented on src/lib/server.ts
> +// TODO for example this would be important for sql.js
Do these TODOs

2024-01-25 23:52 UTC, bdemann commented on src/lib/server.ts
> +                console.log('string');
get rid of this log

2024-01-25 23:52 UTC, bdemann commented on src/lib/server.ts
> +            if (typeof data === 'object') {
do how rust does it and leave a todo

2024-01-26 18:02 UTC, lastmjs commented on src/lib/globals.ts
> +    var _azleExportedIc: typeof ic;
Resolved

2024-01-26 18:04 UTC, lastmjs commented on package.json
> +        "zlib": "^1.0.5"
Resolved

2024-01-26 18:05 UTC, lastmjs commented on src/compiler/compile_typescript_code.ts
> +            zlib: 'crypto-browserify', // TODO wrong of course
Tried and it just broke, so leaving it

2024-01-26 18:06 UTC, lastmjs commented on src/lib/server.ts
> +// TODO for example this would be important for sql.js
I did this in the next PR

2024-01-26 20:47 UTC, bdemann approved these changes

2024-01-26 20:49 UTC, merged