Motoko examples phone book
demergent-labs/azle pull request #160
Opened 2022-04-02 06:00 UTC by tarek-eg

closes https://github.com/demergent-labs/azle/issues/63

2022-04-02 18:54 UTC, lastmjs requested changes
The problems here are similar to superhoes, probably stemming from the www object in the dfx.json being in the wrong place. If you can fix that and test everything, making sure it's an exact clone as far as possible, and replacing any language in the frontend app that refers to Motoko, then this should be awesome!

2022-04-02 18:54 UTC, lastmjs commented on examples/motoko_examples/phone-book/README.md
> +This example demonstrates a phone book application that is accessible from your
Please just link to the original README

2022-04-02 18:54 UTC, lastmjs commented on examples/motoko_examples/phone-book/dfx.json
> +  "www": {
This www object should be within the canisters object

2022-04-02 18:54 UTC, lastmjs commented on examples/motoko_examples/phone-book/README.md
> +   npm install
Same issues as with the superhoes example probably, try to make everything an exact clone as far as possible, use the asset canister

2022-04-03 04:50 UTC, tarek-eg commented
I think I didn't detect the www location issue because I used the npm start command instead which doesn't require the asset canister to be deployed.

2022-04-04 12:35 UTC, lastmjs requested changes

2022-04-04 12:35 UTC, lastmjs commented on .eslintrc
> +  "extends": ["prettier"],
Let's remove this file

2022-04-04 12:36 UTC, lastmjs commented
Looking really good, if you've tested it locally from the asset canister and it works, just remove .eslintrc and I can merge this

2022-04-04 17:22 UTC, tarek-eg commented
@lastmjs this is tested locally and works fine

2022-04-04 17:32 UTC, lastmjs commented
.eslintrc file is still in there

2022-04-04 17:33 UTC, tarek-eg commented
> .eslintrc file is still in there

It was originally there, that's the one in the root

2022-04-04 18:03 UTC, merged