add bitcoin npm lib examples
demergent-labs/azle pull request #1624
Opened 2024-02-07 19:51 UTC by bdemann

2024-02-08 17:30 UTC, lastmjs commented on examples/bitcoinjs-lib/test/tests.ts
> +                            '076595661fbe8eee656defdcb189bdcebeaa34f8dc8115f78c11dfb6f628744b51d16b5d91ff70217084678eeadf479a045eb6530af8d042a7f521622d9a4c38'
Make them all the same

2024-02-08 17:33 UTC, lastmjs commented on examples/bitcore-lib/src/index.ts
> +        console.log(signature);
Remove

2024-02-08 17:33 UTC, lastmjs commented on examples/bitcore-lib/test/pretest.ts
> +    await new Promise((resolve) => setTimeout(resolve, 5000));
Remove

2024-02-08 17:35 UTC, lastmjs commented on examples/bitcore-lib/test/tests.ts
> +            name: '/get-address',
These should match the bitcorejs-lib

2024-04-17 18:49 UTC, bdemann commented on examples/bitcore-lib/test/pretest.ts
> +    await new Promise((resolve) => setTimeout(resolve, 5000));
done

2024-04-17 18:50 UTC, bdemann commented on examples/bitcore-lib/src/index.ts
> +        console.log(signature);
done

2024-04-17 18:54 UTC, bdemann commented on examples/bitcore-lib/src/index.ts
> +            satoshis: 50000
done

2024-04-17 18:55 UTC, bdemann commented on examples/bitcoinjs-lib/test/tests.ts
> +                            '076595661fbe8eee656defdcb189bdcebeaa34f8dc8115f78c11dfb6f628744b51d16b5d91ff70217084678eeadf479a045eb6530af8d042a7f521622d9a4c38'
done

2024-04-17 18:55 UTC, bdemann commented on examples/bitcoinjs-lib/test/tests.ts
> +                            transactionHex ===
done

2024-04-17 18:55 UTC, bdemann commented on examples/bitcoinjs-lib/test/tests.ts
> +                            publicKeyHex ===
done

2024-04-17 18:55 UTC, bdemann commented on examples/bitcoinjs-lib/test/tests.ts
> +                            '1PmamxRspvjCV7vDqMpzvKf92epy1utZVj'
done

2024-04-17 18:56 UTC, bdemann commented on examples/bitcoinjs-lib/test/pretest.ts
> +    await new Promise((resolve) => setTimeout(resolve, 5000));
done

2024-04-17 18:56 UTC, bdemann commented on examples/bitcoinjs-lib/src/index.ts
> +        console.log('about to add input');
done

2024-04-17 18:56 UTC, bdemann commented on examples/bitcoinjs-lib/src/index.ts
> +        const validator = (
done

2024-04-17 18:57 UTC, bdemann commented on examples/bitcoinjs-lib/src/index.ts
> +        keyPair.toWIF();
done

2024-04-17 18:58 UTC, bdemann commented on examples/bitcoinjs-lib/package.json
> +        "i": "^0.3.7",
done

2024-04-17 18:58 UTC, bdemann commented on examples/bitcoinjs-lib/test/tests.ts
> +                    const responseText = await response.json();
done, fail-to-verify-bitcoin-message test has been added

2024-04-17 19:56 UTC, lastmjs requested changes

2024-04-17 19:56 UTC, lastmjs commented on examples/bitcore-lib/test/tests.ts
> +    return [...getBitcoinTests(canisterId)];
Get rid of

2024-04-17 19:56 UTC, lastmjs commented on examples/bitcore-lib/src/index.ts
> +    const utxo = Transaction.UnspentOutput.fromObject({
Let's figure out where we got these

2024-04-17 19:56 UTC, lastmjs commented on examples/bitcoinjs-lib/src/index.ts
> +    const transaction = new bitcoin.Transaction();
let

2024-04-17 19:56 UTC, lastmjs commented on examples/bitcoinjs-lib/src/index.ts
> +    const txHash = Buffer.from(prevTxId, 'hex').reverse();
let

2024-04-17 19:57 UTC, lastmjs approved these changes

2024-04-18 11:25 UTC, lastmjs requested changes

2024-04-18 11:25 UTC, lastmjs commented on examples/bitcoinjs-lib/test/pretest.ts
> +    execSync(`cd ../bitcore-lib && npm install`, { stdio: 'inherit' });
I think this deserves a comment explaining its existence

2024-04-18 11:28 UTC, lastmjs commented on examples/bitcoinjs-lib/test/pretest.ts
> +    execSync(`cd ../bitcore-lib && npm install`, { stdio: 'inherit' });
I'm going to make an issue for this, please address it soon: https://github.com/demergent-labs/azle/issues/1745

2024-04-18 11:28 UTC, lastmjs approved these changes

2024-04-18 11:29 UTC, merged