Update all examples that start with "a" to use jest
demergent-labs/azle pull request #1827
Opened 2024-06-12 18:41 UTC by bdemann

2024-06-13 15:18 UTC, bdemann commented on examples/async_await/test/tests.ts
> +        it('gets randomness even when there are multiple awaits in multiple places at multiple levels', async () => {
"even where there are multiple levels of awaits" -@lastmjs

2024-06-14 03:25 UTC, bdemann commented on examples/async_await/test/tests.ts
> +        it('gets randomness even when there are multiple levels of awaits', async () => {
"even where there are multiple levels of awaits" -@lastmjs

2024-06-14 17:16 UTC, lastmjs requested changes

2024-06-14 17:16 UTC, lastmjs commented on examples/apollo_server/test/tests.ts
> +                headers: [['Content-Type', 'application/json']],
Add X-Ic-Force_query to all GraphQL queries

2024-06-14 17:16 UTC, lastmjs commented on examples/audio_and_video/test/tests.ts
> +import { expect, it, Test } from 'azle/test/jest';
Change Test to something like TestGetter

2024-06-14 17:17 UTC, lastmjs submitted a review, later dismissed

2024-06-14 17:31 UTC, merged