Misc class based syntax clean up
demergent-labs/azle pull request #1880
Opened 2024-07-09 20:23 UTC by bdemann

2024-07-12 18:13 UTC, lastmjs requested changes

2024-07-12 18:13 UTC, lastmjs commented on src/lib/stable/ic_apis/caller.ts
> +        return Principal.fromHex('0x04');
Probably wrong

2024-07-12 18:13 UTC, lastmjs commented on src/lib/stable/ic_apis/id.ts
> +        return Principal.fromHex('0x04');
Probably not the anonymous principal

2024-07-12 18:13 UTC, lastmjs commented on tests/end_to_end/candid_rpc/class_syntax/notify_raw/src/canister1/index.ts
> +                payment: 0n
Is the payment sent with notify raw?

2024-07-12 18:16 UTC, bdemann commented on examples/composite_queries/test/tests.ts
> +        it.only('performs a simple manual query', async () => {
done

2024-07-12 18:21 UTC, bdemann commented on src/compiler/generate_candid_and_canister_methods.ts
done

2024-07-12 18:22 UTC, bdemann commented on src/lib/ic/call.ts
> +        return {} as any;
done

2024-07-12 18:22 UTC, bdemann commented on src/lib/stable/ic_apis/call.ts
> +            return {};
done

2024-07-12 18:28 UTC, bdemann commented on examples/stable_memory/test/tests.ts
done

2024-07-12 18:28 UTC, bdemann commented on examples/stable_memory/test/tests.ts
duplicate

2024-07-12 20:18 UTC, lastmjs requested changes

2024-07-12 20:18 UTC, lastmjs commented on tests/end_to_end/candid_rpc/class_syntax/manual_reply/src/index.ts
Figure out reserved, we should be able to pass anything in, and I think it should be undefined

2024-07-12 22:21 UTC, lastmjs requested changes
Let's use `candidType` and `idlType` convention everywhere

2024-07-15 16:49 UTC, lastmjs submitted a review, later dismissed

2024-07-15 16:52 UTC, merged