Rust experimental
demergent-labs/azle pull request #1999
Opened 2024-08-08 16:01 UTC by lastmjs

2024-08-12 18:40 UTC, bdemann approved these changes

2024-08-12 21:18 UTC, bdemann requested changes
It looks like any test that has assets has to be experimental since it's going to be using the file uploader.

2024-08-19 19:12 UTC, lastmjs commented
I have addressed the issue and added the experimental flag where necessary in the class-based tests

2024-08-19 19:16 UTC, bdemann approved these changes

2024-08-19 19:30 UTC, merged