Quick clean up
demergent-labs/azle pull request #2001
Opened 2024-08-12 19:46 UTC by bdemann

2024-08-16 22:21 UTC, bdemann commented
There is one rust warning left that I want to ask about

2024-08-19 19:27 UTC, lastmjs requested changes

2024-08-19 19:27 UTC, lastmjs commented on experimental/canisters/ledger/address/index.ts
> +import { Principal } from '../../..';
Why was Principal left?

2024-08-19 19:27 UTC, lastmjs commented on src/compiler/rust/canister/src/lib.rs
Remove this file

2024-08-19 19:38 UTC, lastmjs submitted a review, later dismissed

2024-08-19 21:23 UTC, lastmjs approved these changes

2024-08-19 21:37 UTC, merged