Class based prop tests
demergent-labs/azle pull request #2002
Opened 2024-08-16 18:52 UTC by bdemann

2024-08-20 16:55 UTC, lastmjs requested changes
We should move the rest of the property_test stuff

2024-08-20 16:57 UTC, lastmjs commented
Move property_tests into test/property

2024-08-20 17:00 UTC, lastmjs requested changes
Please implement all requests across all PRs

2024-08-20 20:25 UTC, lastmjs submitted a review, later dismissed

2024-08-20 20:36 UTC, lastmjs approved these changes

2024-08-20 21:29 UTC, lastmjs approved these changes

2024-08-22 20:48 UTC, lastmjs requested changes

2024-08-22 20:48 UTC, lastmjs commented on property_tests/arbitraries/candid/candid_type.ts
> +        return 'number[]';
What's this?

2024-08-22 20:48 UTC, lastmjs commented on property_tests/arbitraries/candid/candid_type.ts
> +        return 'number[]';
Seems like it should be Uint8Array

2024-08-22 21:47 UTC, bdemann commented on property_tests/arbitraries/candid/candid_type.ts
> +        return 'number[]';
done

2024-08-22 22:17 UTC, lastmjs requested changes

2024-08-22 22:25 UTC, lastmjs commented on property_tests/arbitraries/types.ts
> +export type Context<Constraint = any> = {
Let's get rid of the any...union of the concrete constraint types?

2024-08-22 22:26 UTC, lastmjs commented on property_tests/arbitraries/types.ts
> +export type Context<Constraint = any> = {
The default value should be undefined...but we need to constrain the type with extends

2024-08-22 22:27 UTC, lastmjs commented on property_tests/arbitraries/types.ts
> +export type Context<Constraint = any> = {
Let's make constraints optional

2024-08-22 22:37 UTC, lastmjs requested changes

2024-08-22 22:37 UTC, lastmjs commented on tests/property/candid_rpc/class_syntax/canister_methods/init/test/generate_callable_method_body.ts
> +        (param) => `console.log(${param.name})`
console.info

2024-08-23 15:36 UTC, bdemann commented on property_tests/arbitraries/candid/candid_definition_arb/index.ts
> +                    constraints: constraints?.weights
yes, the constraints for primitive and the weights object have the same shape

2024-08-23 15:38 UTC, bdemann commented on property_tests/arbitraries/candid/candid_definition_arb/index.ts
> +                    { api, constraints: undefined }, // TODO was it the old way to not have constraints here? Should it be?
done

2024-08-23 15:38 UTC, bdemann commented on property_tests/arbitraries/candid/candid_definition_arb/recursive_candid_definition_memo.ts
> +            { ...context, constraints: { depthLevel: depthLevel } },
done

2024-08-23 15:39 UTC, bdemann commented on tests/property/candid_rpc/class_syntax/blob/test/test.ts
> +const context = { api, constraints: {} };
It made more sense to have essentially an empty list of constraints than undefined

2024-08-23 15:40 UTC, bdemann commented on tests/property/candid_rpc/class_syntax/canister_methods/init/test/generate_callable_method_body.ts
> +        (param) => `console.log(${param.name})`
done

2024-08-23 15:41 UTC, bdemann commented on tests/property/candid_rpc/class_syntax/blob/test/test.ts
> +const context = { api, constraints: {} };
This will likely get address or disregarded with the comment above about `export type Context<Constraint = any> = {`

2024-08-23 17:20 UTC, lastmjs submitted a review, later dismissed

2024-08-23 17:47 UTC, lastmjs commented on property_tests/arbitraries/types.ts
> +export type Context<Constraint = any> = {
We're performing the final changes on this

2024-08-23 20:32 UTC, bdemann commented on property_tests/arbitraries/types.ts
> +export type Context<Constraint = any> = {
done

2024-08-23 20:51 UTC, lastmjs approved these changes

2024-08-23 21:35 UTC, merged