Class based prop tests almost done
demergent-labs/azle pull request #2011
Opened 2024-08-20 16:02 UTC by bdemann

2024-08-20 16:51 UTC, lastmjs requested changes

2024-08-20 16:51 UTC, lastmjs commented on property_tests/tests/class_syntax/stable_b_tree_map/test/utils.ts
Is this not completely broken now for class-based syntax?

2024-08-20 16:51 UTC, lastmjs commented on property_tests/arbitraries/candid/candid_values_arb.ts
> +        return FunctionalServiceValueArb(
Discuss adding syntax everywhere

2024-08-22 21:39 UTC, bdemann commented on property_tests/arbitraries/candid/candid_values_arb.ts
> +        return FunctionalServiceValueArb(
done

2024-08-22 22:25 UTC, bdemann commented on property_tests/tests/class_syntax/stable_b_tree_map/test/utils.ts
done

2024-08-23 21:56 UTC, closed without merging