Quick tests
demergent-labs/azle pull request #2081
Opened 2024-09-09 20:58 UTC by bdemann

2024-09-17 22:51 UTC, lastmjs requested changes

2024-09-17 22:51 UTC, lastmjs commented on tests/end_to_end/http_server/large_files/test/auto_tests.ts
>      process.env.AZLE_TEST_RUN_ON_RELEASE === 'true' ||
Prefix all env variables in test.yml

2024-09-17 22:51 UTC, lastmjs commented on tests/end_to_end/http_server/large_files/test/auto_tests.ts
>      process.env.AZLE_TEST_RUN_ON_RELEASE === 'true' ||
Rename to AZLE_TEST_RUN_ON_RELEASE_BRANCH_PR

2024-09-17 22:51 UTC, lastmjs commented on tests/end_to_end/http_server/large_files/test/auto_tests.ts
>      process.env.AZLE_TEST_RUN_ON_RELEASE === 'true' ||
Let's just use the regular test.yml variables, but prefixed with AZLE_. We should explicitly put in each case (release branch pr, main commit thing)

2024-09-19 19:59 UTC, lastmjs requested changes

2024-09-19 19:59 UTC, lastmjs commented on .github/workflows/test.yml
> +                  # Exclude RELEASE_TESTS if it's not a release pr
One if statement per branch/push type

2024-09-19 19:59 UTC, lastmjs commented on .github/workflows/test.yml
>              - name: Start dfx without artificial delay
Start dfx with artificial delay 0

2024-09-19 19:59 UTC, lastmjs commented on .github/workflows/test.yml
> +                  if ${{ env.AZLE_IS_MAIN_BRANCH_PUSH }}; then
Same order as definition

2024-09-19 20:02 UTC, bdemann commented on .github/workflows/test.yml
> +                  # Exclude RELEASE_TESTS if it's not a release pr
done

2024-09-19 20:02 UTC, bdemann commented on .github/workflows/test.yml
>              - name: Start dfx without artificial delay
done

2024-09-19 20:02 UTC, bdemann commented on .github/workflows/test.yml
> +                  if ${{ env.AZLE_IS_MAIN_BRANCH_PUSH }}; then
done

2024-09-19 20:06 UTC, lastmjs requested changes
Add liney line breaks

2024-09-19 20:08 UTC, lastmjs approved these changes

2024-09-19 20:13 UTC, merged