add error message to markdown if benchmarks failed
demergent-labs/azle pull request #2300
Opened 2024-12-05 18:59 UTC by bdemann

2024-12-09 22:33 UTC, lastmjs requested changes

2024-12-09 22:33 UTC, lastmjs commented on package.json
> +    "version": "0.25.0-dev.2",
Is this a relic of testing?

2024-12-10 19:39 UTC, bdemann commented on package.json
> +    "version": "0.25.0-dev.2",
removed

2024-12-10 23:21 UTC, lastmjs approved these changes

2024-12-10 23:23 UTC, merged