Add motoko echo example
demergent-labs/azle pull request #289
Opened 2022-05-17 03:50 UTC by dansteren

This implements the Motoko echo example found here: https://github.com/dfinity/examples/tree/master/motoko/echo, with a single test (since this is a straightforward example).

Resolves https://github.com/demergent-labs/azle/issues/56

2022-05-17 13:04 UTC, lastmjs requested changes

2022-05-17 13:04 UTC, lastmjs commented on examples/motoko_examples/echo/test/test.ts
> +        name: 'say',
Let's just put a few more tests in here

2022-05-17 13:04 UTC, lastmjs commented
Remember to put the notices and licenses in here

2022-05-19 19:32 UTC, lastmjs requested changes

2022-05-19 19:32 UTC, lastmjs commented on examples/motoko_examples/echo/test/test.ts
> +            `
semicolon

2022-05-19 19:32 UTC, lastmjs commented on examples/motoko_examples/echo/test/test.ts
> +            const phrase = ""
Single quotes in JS, and semicolon

2022-05-19 19:32 UTC, lastmjs commented on examples/motoko_examples/echo/test/test.ts
> +            const phrase = "This is a test."
Single quotes in JS, and semicolon

2022-05-23 17:19 UTC, lastmjs approved these changes

2022-05-23 18:33 UTC, lastmjs requested changes

2022-05-23 18:33 UTC, lastmjs commented on .github/workflows/test.yml
> +            "examples/motoko_examples/echo"
Needs a comma

2022-05-23 18:36 UTC, dansteren commented on .github/workflows/test.yml
> +            "examples/motoko_examples/echo"
Added missing comma.

2022-05-23 18:53 UTC, lastmjs approved these changes

2022-05-23 18:53 UTC, merged