405 http counter motoko example
demergent-labs/azle pull request #430
Opened 2022-06-20 19:11 UTC by bdemann

2022-06-21 17:43 UTC, lastmjs requested changes

2022-06-21 17:43 UTC, lastmjs commented on examples/motoko_examples/http_counter/package.json
> +    "azle": "^0.4.0",
Please remove all carots `^` and merge with main and run prettier, `npx prettier --write .`

2022-06-21 17:43 UTC, lastmjs commented on examples/motoko_examples/http_counter/package.json
> +  "main": "index.js",
If you could copy the other examples' package.json files, let's remove any fields that the others do not have (like main) and set the version similar to other versions

2022-06-21 17:43 UTC, lastmjs commented on examples/motoko_examples/http_counter/src/main.ts
> +let counter = 0;
Did we decide not to implement stable storage here? If we didn't, then let's do so

2022-06-21 17:43 UTC, lastmjs commented on examples/motoko_examples/http_counter/src/main.ts
> +            // Currently there is an issue with azle being able to process the above string from the motoko example.
If you could prefix these comments with `TODO`, that's a convention used throughout the codebase that'll make it easy to find these. A `TODO` comment is something that should be addressed, and isn't simply there for informational purposes.

2022-06-30 21:23 UTC, dansteren approved these changes

2022-06-30 21:23 UTC, merged