change getCount from Update to Query
demergent-labs/azle pull request #455
Opened 2022-06-30 16:21 UTC by bdemann

2022-06-30 19:15 UTC, dansteren commented
Can you manually run prettier on your files (`npx prettier --write .`)? I think that's where the majority of the changes in this PR are from. I think even though the files are auto-generated by `dfx generate` we are still running them through prettier. So each time you run `dfx generate` run prettier after. We can work on getting it in a pre-commit hook. Just haven't gotten it that far yet.

2022-06-30 21:53 UTC, lastmjs requested changes

2022-06-30 21:53 UTC, lastmjs commented on examples/motoko_examples/minimal-counter-dapp/src/declarations/minimal_dapp/index.js
> +import { Actor, HttpAgent } from "@dfinity/agent";
First step, if you could run `npx prettier --write .`, that will clean up a lot of these files.

2022-07-01 01:18 UTC, lastmjs commented on examples/motoko_examples/minimal-counter-dapp/src/declarations/minimal_dapp/index.js
> +import { Actor, HttpAgent } from "@dfinity/agent";
Then incorporate the latest from main and push then this should be good

2022-07-01 18:03 UTC, lastmjs approved these changes

2022-07-01 18:04 UTC, merged