Add benchmarks for examples/update
demergent-labs/azle pull request #516
Opened 2022-07-12 23:40 UTC by dansteren

This adds a Rust and Motoko implementation of this example and benchmarks for all 3 implementations.

Resolves #501

2022-07-29 16:31 UTC, lastmjs requested changes

2022-07-29 16:31 UTC, lastmjs commented on examples/update/canisters/azle/index.ts
> +export function query(): Query<string> {
The Azle and Motoko names for this function should be the same, perhaps something like `get_current_message` would be better than `query1`?

2022-07-29 16:31 UTC, lastmjs commented on examples/update/canisters/motoko/main.mo
> +  public query func query1() : async Text {
The Azle and Motoko names for this function should be the same, perhaps something like `get_current_message` would be better than `query1`?

2022-07-29 16:31 UTC, lastmjs commented on examples/update/canisters/rust/src/lib.rs
> +    static CURRENT_MESSAGE: RefCell<String> = RefCell::new(String::from(""));
Rename to `CURRENT_MESSAGE_REF_CELL`

2022-07-29 16:31 UTC, lastmjs commented on examples/update/canisters/rust/src/lib.rs
> +    static CURRENT_MESSAGE: RefCell<String> = RefCell::new(String::from(""));
Our convention is "".to_string()

2022-07-29 16:31 UTC, lastmjs commented on examples/update/canisters/rust/src/lib.rs
> +    CURRENT_MESSAGE.with(|current_message| current_message.borrow().clone())
Rename to `CURRENT_MESSAGE_REF_CELL` and `current_message_ref_cell`

2022-07-29 16:31 UTC, lastmjs commented on examples/update/canisters/rust/src/lib.rs
> +    CURRENT_MESSAGE.with(|current_message| {
Rename to `CURRENT_MESSAGE_REF_CELL` and `current_message_ref_cell`

2022-07-29 16:31 UTC, lastmjs commented on examples/update/dfx.json
> +            "main": "canisters/motoko/main.mo",
Let's keep the dfx.json files using the same conventions, the motoko should have type: motoko, and the rust should have type: rust first, then package, then candid

2022-07-29 16:31 UTC, lastmjs commented on examples/update/package.json
> +        "benchmark": "ts-node --transpile-only --ignore=false benchmark/benchmark.ts",
The convention has been to put benchmark below test, if we want to change that we should do it across all of the examples

2022-08-02 17:42 UTC, dansteren commented on examples/update/canisters/rust/src/lib.old.did
> +}
:man_facepalming: Need to remove this

2022-08-02 19:36 UTC, lastmjs requested changes

2022-08-02 19:36 UTC, lastmjs commented on examples/update/benchmarks.md
> +# Azle/Motoko/Rust Benchmarks
Let's run this again with USD Cost estimates

2022-08-02 19:36 UTC, lastmjs commented on examples/update/canisters/rust/src/lib.old.did
> +}
Remove this

2022-08-03 15:14 UTC, merged