add motoko and rust examples to motoko_examples/hello-world
demergent-labs/azle pull request #549
Opened 2022-07-20 13:34 UTC by bdemann

2022-07-20 18:17 UTC, dansteren requested changes
Overall very good. It looks like you aren't including dfx generated files for motoko which we'll need for benchmarks. And then make sure to comment out the final line in the generated index.js files.

2022-07-20 18:17 UTC, dansteren commented on examples/motoko_examples/hello-world/dfx_generated/azle/index.js
> +export const azle = createActor(canisterId);
Comment out this line.

2022-07-20 18:17 UTC, dansteren commented on examples/motoko_examples/hello-world/dfx_generated/rust/index.js
> +export const rust = createActor(canisterId);
Comment out this line.

2022-08-02 17:54 UTC, lastmjs submitted a review, later dismissed

2022-08-02 17:55 UTC, merged