add rust and motoko examples to echo
demergent-labs/azle pull request #550
Opened 2022-07-20 14:56 UTC by bdemann

2022-07-20 18:02 UTC, dansteren requested changes
Looks really good. You just need to comment out the last lines in the agent files so that we can use them in our tests/benchmarks.

2022-07-20 18:02 UTC, dansteren commented on examples/motoko_examples/echo/dfx_generated/motoko/index.js
> +export const motoko = createActor(canisterId);
We're going to need this line commented out to be able to use it in our tests or benchmarks.

2022-07-20 18:02 UTC, dansteren commented on examples/motoko_examples/echo/dfx_generated/azle/index.js
> +export const azle = createActor(canisterId);
Comment out this last line.

2022-07-20 18:02 UTC, dansteren commented on examples/motoko_examples/echo/dfx_generated/rust/index.js
> +export const rust = createActor(canisterId);
Comment out this line.

2022-07-20 18:13 UTC, dansteren commented
The other thing I noticed is that some of your files don't have a final newline character. We should be adding final newlines to all files since that's how [POSIX defines a line](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_206). You can see this in your PRs where the files have a :no_entry: emoji at the very end. Fortunately, this is a really easy problem to solve. Just enable the "Files: Insert Final Newline" setting in VS Code:
![image](https://user-images.githubusercontent.com/5455419/180052794-0357164d-991d-48c9-966f-7ccc7b6f2882.png)
While you're at it I would also recommend you enable "Files: Trim Final Newlines" and "Files: Trim Trailing Whitespace".

Ideally we'd have a `.editorconfig` in our repo that would ensure this happens but manually setting it for now should be sufficient.

2022-08-02 17:58 UTC, lastmjs approved these changes

2022-08-02 17:59 UTC, merged