77 standardize error reporting
demergent-labs/azle pull request #724
Opened 2022-10-11 15:09 UTC by bdemann

2022-10-11 16:24 UTC, bdemann commented on src/compiler/typescript_to_rust/azle_generate/src/generators/cross_canister_call_functions/mod.rs
> +impl GenerateCrossCanisterCallFunctionsInfos for Vec<AzleTypeAlias<'_>> {
Make sure that all of the names of things that used to be TsTypeAliasDecls are updated to reflect becoming AzleTypeAliases. Make sure that TsTypeAliasDecls are all wrapped in AzleTypeAliases by making sure that they are only directly used in the AzleTypeAlias module

2022-10-11 16:24 UTC, bdemann commented on src/compiler/typescript_to_rust/azle_generate/src/generators/type_aliases.rs
> +    ts_ast::{type_alias::azle_type_alias::TsTypeAliasListHelperMethods, AzleTypeAlias},
Rename TsTypeAliasListHelperMethods to be be AzleTypeAliasListHelperMethods

2022-10-11 16:25 UTC, bdemann commented on src/compiler/typescript_to_rust/azle_generate/src/ts_ast/ast_traits/get_name.rs
> +impl GetName for swc_ecma_ast::TsCallSignatureDecl {
Clean up these todos and make it more clear what we actually have todo here

2022-10-11 16:26 UTC, bdemann commented on src/compiler/typescript_to_rust/azle_generate/src/ts_ast/ast_traits/mod.rs
> +impl GetName for TsFnParam {
Move this to the TsFnParam file

2022-10-11 16:30 UTC, bdemann commented on src/compiler/typescript_to_rust/azle_generate/src/ts_ast/program/azle_program.rs
> +pub trait TsProgramVecHelperMethods {
Rename this to be AzleProgram

2022-10-11 16:30 UTC, bdemann commented on src/compiler/typescript_to_rust/azle_generate/src/ts_ast/module.rs
> +        let export_type_alias_decls: Vec<AzleTypeAlias> = export_decls
Rename to export_azle_type_alias

2022-10-11 16:32 UTC, bdemann commented on src/compiler/typescript_to_rust/azle_generate/src/ts_ast/program/system_canister_method_builder/heartbeat.rs
> +    ts_ast::program::{azle_program::TsProgramVecHelperMethods, AzleProgram},
Make these imports better

2022-10-11 16:34 UTC, bdemann commented on src/compiler/typescript_to_rust/azle_generate/src/ts_ast/program/system_canister_method_builder/pre_upgrade.rs
> +    ts_ast::program::{azle_program::TsProgramVecHelperMethods, AzleProgram},
fix this import

2022-10-11 16:40 UTC, bdemann commented on src/compiler/typescript_to_rust/azle_generate/src/ts_ast/ts_ast.rs
> +        // let source_map_option = self.azle_programs.iter().find(|azle_program| {
Get rid of this comment

2022-10-11 16:45 UTC, bdemann commented on src/compiler/typescript_to_rust/azle_generate/src/ts_ast/ts_tuple_type.rs
> +impl GetString for TsTupleType {
This shouldn't be in here anymore

2022-10-11 16:53 UTC, bdemann commented on src/compiler/typescript_to_rust/azle_generate/src/ts_ast/ts_type.rs
> +// TODO I am wondering if to_string() might make more sense for these? I just am
Resolve this comment

2022-10-11 16:56 UTC, bdemann commented on src/compiler/typescript_to_rust/azle_generate/src/ts_ast/ts_type_ref.rs
> +        type_alias_lookup: &HashMap<String, AzleTypeAlias>,
rename this

2022-10-11 23:06 UTC, lastmjs requested changes

2022-10-12 20:00 UTC, bdemann commented on src/compiler/typescript_to_rust/azle_generate/src/cdk_act/generators/ic_object/mod.rs
> +use crate::ts_ast::program::AzleProgram;
https://github.com/demergent-labs/azle/issues/725

2022-10-12 20:00 UTC, bdemann commented on src/compiler/typescript_to_rust/azle_generate/src/cdk_act/generators/ic_object/mod.rs
> +pub trait IcObjectHelperMethods {
https://github.com/demergent-labs/azle/issues/725

2022-10-12 20:00 UTC, bdemann commented on src/compiler/typescript_to_rust/azle_generate/src/ts_ast/fn_decl/canister_method_builder.rs
>  impl CanisterMethodBuilder for FnDecl {
Yes we will wrap as we go

2022-10-12 20:03 UTC, bdemann commented
Closing if favor of this
https://github.com/demergent-labs/azle/pull/726
which has only the addition of SoruceMaps and AzleTypeAliasDecls

2022-10-12 20:03 UTC, closed without merging