Fixed inline types
demergent-labs/azle pull request #878
Opened 2023-01-25 07:28 UTC by dansteren

Ensure that inline types work in records, vecs, opts, funcs, and variants.

> **Warning**
> Depends on https://github.com/demergent-labs/cdk_framework/pull/21

2023-01-25 19:05 UTC, lastmjs requested changes

2023-01-25 22:26 UTC, dansteren commented on examples/inline_types/src/inline_types.ts
> +    string,
Added in ca0012737d5803184ae154d36ce93ef630233452

2023-01-25 22:27 UTC, dansteren commented on examples/inline_types/test/dfx_generated/inline_types/index.d.ts
> +import type {
Done in c5ff2be9eba208d43bb00a6e82e2249c5c6d09dd

2023-01-26 22:14 UTC, lastmjs approved these changes

2023-01-26 22:14 UTC, merged